# SPDX-FileCopyrightText: GitHub, Inc.
# SPDX-License-Identifier: MIT

seclab-taskflow-agent:
  filetype: taskflow
  version: "1.0"
model_config: seclab_taskflows.configs.model_config

globals:
  repo:
  use_advisory:
# Taskflow to analyze the general contextual information of a project and classify the different applications within it
taskflow:
  - task:
      must_complete: true
      exclude_from_context: true
      agents:
        - seclab_taskflow_agent.personalities.assistant
      model: general_tasks
      user_prompt: |
        Fetch the components of the repo {{ globals.repo }}
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
  - task:
      must_complete: true
      repeat_prompt: true
      async: true
      agents:
        - seclab_taskflows.personalities.web_application_security_expert
      model: code_analysis
      user_prompt: |
        The component is in the repo {{ result.repo }} and it has component id {{ result.app_id }} and location {{ result.location }}.
        The notes of the component is as follows.

        {{ result.notes }}

        Fetch the entry points and web entry points of the component, then the user actions of this component.
        Based on the entry points, web entry points, components, user actions and README.md and if available, SECURITY.md in the {{ globals.repo }},
        can you tell me what type of application this repo is and what kind of security boundary it has.
        Based on this, determine whether the component is likely to have security problems.

        {% if globals.use_advisory == 'true' %}
        {% include 'seclab_taskflows.prompts.audit.known_security_advisories' %}
        {% endif %}

        {% if result.is_library %}
        {% include 'seclab_taskflows.prompts.audit.classify_library_component' %}
        {% else %}
        {% include 'seclab_taskflows.prompts.audit.classify_application_component' %}
        {% endif %}

        It is not your task to audit the security measures, but rather just to identify the risks and suggest some issues
        that is worth auditing.

        Reflect on your notes and check that the attack scenario meets the above requirements. Exclude low severity issues or
        issues that require unrealistic circumstances such as misconfiguration or stolen credentials etc.
        It is ok to conclude that the component is not likely to have security issues.

        If you think the issues satisfy the criteria, store a component issue entry for each type of issue identified.
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
        - seclab_taskflows.toolboxes.container_shell_source_access
        - seclab_taskflows.toolboxes.ghsa
  - task:
      must_complete: true
      exclude_from_context: true
      agents:
        - seclab_taskflow_agent.personalities.assistant
      model: general_tasks
      user_prompt: |
        Fetch the components of the repo {{ globals.repo }}
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
  - task:
      must_complete: true
      repeat_prompt: true
      async: true
      max_steps: 100
      name: analyze_security_entry_points
      agents:
        - seclab_taskflows.personalities.web_application_security_expert
      model: code_analysis
      user_prompt: |
        The component is in the repo {{ result.repo }} and it has component id {{ result.app_id }} and location {{ result.location }}.
        The notes of the component is as follows.

        {{ result.notes }}

        Fetch the security entry points component, then the user actions of this component.
        Based on the security entry points, components, user actions and README.md and if available, SECURITY.md in the {{ globals.repo }},
        can you tell me what type of application this repo is and what kind of security boundary it has.

        For each security entry point, identify the type of the security entry point and its functionality. 
        These entry points should be performing some kind of security sensitive operations, such as authentication, authorization, input validation, sanitization, escaping etc.
        Identify the functionality of the entry point and what kind of issue may arise if the implementation is flawed. 
        For example, an authentication entry point may be susceptible to authentication bypass, 
        an input validation entry point may be susceptible to injection issues if the input is not properly sanitized, 
        an authorization entry point may be susceptible to IDOR or access control bypass if there are no proper access control checks.
        This task is only to identify the potential risks and issues that may arise from the type of the security entry point, 
        rather than auditing the implementation of the entry point, so do not be too specific about the issue, and do not 
        audit the implementation, just identify the potential risks based on the type and functionality of the security entry point.
        However, you should still take care not to include issues that are of low severity or require
        unrealistic attack scenarios such as misconfiguration or an already compromised system, or issues that requires 
        attacker control of trusted inputs such as whitelist or blacklist bypass that requires the attacker 
        to be able to modify the whitelist or blacklist.

        Reflect on your notes and check that the attack scenario meets the above requirements. Exclude low severity issues or
        issues that require unrealistic circumstances such as misconfiguration or stolen credentials etc.
        It is ok to conclude that the component is not likely to have security issues.

        If you think the issues satisfy the criteria, store a component issue entry for each type of issue identified.
        
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
        - seclab_taskflows.toolboxes.container_shell_source_access
        - seclab_taskflows.toolboxes.ghsa