# SPDX-FileCopyrightText: GitHub, Inc.
# SPDX-License-Identifier: MIT

seclab-taskflow-agent:
  filetype: taskflow
  version: "1.0"
model_config: seclab_taskflows.configs.model_config

globals:
  repo: 
# Taskflow to analyze the general contextual information of a project and classify the different applications within it
taskflow:
  - task:
      must_complete: true
      headless: true
      model: general_tasks
      agents:
        - seclab_taskflow_agent.personalities.assistant
      user_prompt: |
        Clear the memory cache and clear the repo context results for repo {{ globals.repo }}
      toolboxes:
        - seclab_taskflow_agent.toolboxes.memcache
        - seclab_taskflows.toolboxes.repo_context
  - task:
      model: code_analysis
      must_complete: true
      max_steps: 100
      name: identify components
      description: Identify different components and purpose of the repo
      agents:
        - seclab_taskflows.personalities.web_application_security_expert
      user_prompt: |
        Inspect {{ globals.repo }} and determine its function. Determine whether the repo is a framework library,
        or a web application etc. For repos that may contain multiple applications, determine the purpose of each
        application and the directories of each application. Repos can also be libraries but contain actual applications, for
        example, a web server and admin UI etc. that are not for testing or examples.
        
        Apart from source code, it is also useful to look at the README.md and documentations in 
        the repo.

        Note that even a software library may contain application components. 
        For example, a web application framework may contain a default web application as an example or demo, 
        or it may contain an admin UI, which are meant to be used for production.

        Separate the components of the library based on their functionality. For example, full stack web framework may 
        have components for handling http requests, components for database access, components for rendering UI, etc.

        For each application identified, store a new component entry in the database. Provide some brief notes about the 
        functionality of the component with the entry.

        
        Identify example, demo or test code in the repo. Skip analyzing these code and do not create a component entry for these.
      toolboxes:
        - seclab_taskflows.toolboxes.local_file_viewer
        - seclab_taskflows.toolboxes.repo_context
  
  - task:
      must_complete: true
      exclude_from_context: true
      model: general_tasks
      agents:
        - seclab_taskflow_agent.personalities.assistant
      user_prompt: |
          Fetch the components from the repo {{ globals.repo }}.
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
  - task:
      model: code_analysis
      must_complete: false
      repeat_prompt: true
      async: true
      max_steps: 100
      name: entry point analysis
      description: Identify entry points that allow untrusted users to interact with the component.
      agents:
        - seclab_taskflows.personalities.web_application_security_expert
      user_prompt: |
        The component is in {{ result.repo }} in the directory {{ result.location }}. These are the 
        notes for this component:

        {{ result.notes }}

        Analyze the entry points of this application. First check whether this component is a library or 
        an application. 
        {% if result.is_library %}
        {% include 'seclab_taskflows.prompts.audit.entry_point_library' %}
        {% else %}
        {% include 'seclab_taskflows.prompts.audit.entry_point_application' %}
        {% endif %}

        Only identify the untrusted inputs and entry points, do not analyze the security risks of the component or the 
        entry point.

        Once you're finished with this, store an "entry_point" for each entry point identified, providing the precise
        file and line number of this entry point, as well as the user inputs that it exposes. Use the "notes" field to 
        explain how the entry point is exposed to the end user and why the identified user inputs are untrusted. 
        Note that line number has to be integer. If an entry point spans multiple lines, then use the first line as the line 
        number.

        ## IMPORTANT: General Guidance that ALWAYS applies

        1. Do NOT ask the user for permission to perform next steps, continue your
        analysis autonomously until it is complete.
        
        2. Reflect on your analysis for accuracy before returning it to the user.
        We are only interested in results that you can clearly explain and
        motivate as potentially vulnerable based on code examples.

        3. Do NOT speculate. All answers should be motivated by code examples and
        match the conditions of our described vulnerability pattern. Call out
        any situation where you are unsure about your results.

      toolboxes:
        - seclab_taskflows.toolboxes.local_file_viewer
        - seclab_taskflows.toolboxes.repo_context
  - task:
      must_complete: true
      exclude_from_context: true
      model: general_tasks
      agents:
        - seclab_taskflow_agent.personalities.assistant
      user_prompt: |
          Fetch the components from the repo {{ globals.repo }}.
      toolboxes:
        - seclab_taskflows.toolboxes.repo_context
  - task:
      model: code_analysis
      must_complete: false
      repeat_prompt: true
      async: true
      max_steps: 100
      name: user actions analysis
      description: Identify actions that untrusted users are allowed performed the component.
      agents:
        - seclab_taskflows.personalities.web_application_security_expert
      user_prompt: |
        The component is in {{ result.repo }} in the directory {{ result.location }}. These are the 
        notes for this component:

        {{ result.notes }}

        Analyze the actions that an untrusted user is allowed to perform. The purpose of this task is not 
        about the security of the source code, but rather get an understanding of the purpose of the component and 
        what an untrusted user should be allowed to do under the intention of the component.
        For example, the component may have an api that allows an untrusted user to run aribitrary command. In this 
        case, the intention and purpose of the component is for user to run arbitrary command, and so the user action in 
        this case is arbitrary code execution. 

        Similarly, an api may allow a user to read and write files to a specific directory. In this case the intention and 
        the user action is to read and write to restricted directory. This is different to allowing a user read and write 
        to any directories. Be precise in these details when looking at user action.

        Do not consider security risk or potential bypasses or any potential privilege escalations that is outside of the 
        intended use. Focus only on the intended use here.

        {% if result.is_library %}
        {% include 'seclab_taskflows.prompts.audit.user_action_library' %}
        {% else %}
        {% include 'seclab_taskflows.prompts.audit.user_action_application' %}
        {% endif %}
        
        Store an user_action entry stating precising the file and line number where the allowed action is performed, and
        provide notes about the action.

        Note that line number has to be integer. If an user action spans multiple lines, then use the first line as the line 
        number.

        ## IMPORTANT: General Guidance that ALWAYS applies

        1. Do NOT ask the user for permission to perform next steps, continue your
        analysis autonomously until it is complete.
        
        2. Reflect on your analysis for accuracy before returning it to the user.
        We are only interested in results that you can clearly explain and
        motivate as potentially vulnerable based on code examples.

        3. Do NOT speculate. All answers should be motivated by code examples and
        match the conditions of our described vulnerability pattern. Call out
        any situation where you are unsure about your results.

      toolboxes:
        - seclab_taskflows.toolboxes.local_file_viewer
        - seclab_taskflows.toolboxes.repo_context